all: nigga_fag_work

compile_flags=`cmake --find-package -DNAME=SymEngine -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=COMPILE`
link_flags=`cmake --find-package -DNAME=SymEngine -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=LINK`

nigga_fag_work:
	g++ $(compile_flags) ./symengine.cpp $(link_flags) -std=c++17
